### ISSUE TITLE
Add support for XW-210-I

### ISSUE THREAD

**Issue by joshtbernstein** [black-ops-drivers/control4-controlbyweb#4]
I gave this a try with a XW-210-I, but the driver gives the following error when logging is enabled:

```[ERROR]: An error occurred refreshing status; driver.lua:5157: Unbalanced Tag (/BODY) [char=177]```

Please let me know what other info I can provide.

**Comment by black-ops-drivers** [comment]
Have you confirmed your ip and user/pass is correct? If so, can you paste contents from `http://<cbw-ip>/state.xml` and `http://<cbw-ip>/diagnostics.xml` here?

**Comment by joshtbernstein** [comment]
> Have you confirmed your ip and user/pass is correct? If so, can you paste contents from `http://<cbw-ip>/state.xml` and `http://<cbw-ip>/diagnostics.xml` here?

Turns out the XW-210-I doesn't support diagnostics.xml. It only has state.xml which provides the following:

```xml
<datavalues>
<input1state>0</input1state>
<relay1state>0</relay1state>
<units>F</units>
<sensor1>x.x</sensor1>
<sensor2>x.x</sensor2>
<sensor3>x.x</sensor3>
<sensor4>x.x</sensor4>
<s1Alrm>0</s1Alrm>
<s2Alrm>0</s2Alrm>
<s3Alrm>0</s3Alrm>
<s4Alrm>0</s4Alrm>
<count1>23</count1>
<register1>0.00</register1>
<register2>0.00</register2>
<register3>0.00</register3>
<register4>0.00</register4>
<vin>9.577</vin>
<time>1343647469</time>
</datavalues>
```

Modifying the code a bit, I got it to connect, but it's not pulling the input or relay states.

Source: [User Manual Page 58](https://controlbyweb.com/wp-content/uploads/2024/02/webrelay-wireless-users-manual.pdf)

**Comment by black-ops-drivers** [comment]
Yeah that module has a slightly different api response for inputs and relays. Let me take a look and see about changing the code to handle it.

**Comment by black-ops-drivers** [comment]
Can you try the attached driver and let me know if it works? If not, please turn on logging and paste them back here.

[control4-controlbyweb.zip](https://github.com/user-attachments/files/17624977/control4-controlbyweb.zip)

**Comment by joshtbernstein** [comment]
That version didn't work at all. Is it correct that it's version 20240117?

```
Mon Nov  4 15:53:44 2024 [WARN ]: Log mode 'Print' will expire in 3 hours
Mon Nov  4 15:53:46 2024 [TRACE]: API:isConfigured()
Mon Nov  4 15:53:46 2024 [DEBUG]: Fetching device statuses from the API (timer expired)
Mon Nov  4 15:53:46 2024 [TRACE]: API:hasApiFailure()
Mon Nov  4 15:53:46 2024 [TRACE]: RefreshStatus()
Mon Nov  4 15:53:46 2024 [TRACE]: API:getStatus()
Mon Nov  4 15:53:46 2024 [TRACE]: API:_get()
Mon Nov  4 15:53:46 2024 [TRACE]: API:isConfigured()
Mon Nov  4 15:53:46 2024 [TRACE]: API:_createUrl(/state.xml?showUnits=1)
Mon Nov  4 15:53:46 2024 [TRACE]: Http:request(GET, http://[USERNAME]:[PASSWORD]@[IP]/state.xml?showUnits=1, nil, nil, {"return_http_failure":true})
Mon Nov  4 15:53:46 2024 [TRACE]: API:hasAuthenticationFailure()
Mon Nov  4 15:53:46 2024 [TRACE]: Http:getDefaultTimeout()
Mon Nov  4 15:53:46 2024 [TRACE]: Http:getDefaultTimeout()
Mon Nov  4 15:53:46 2024 [TRACE]: API:_get()
Mon Nov  4 15:53:46 2024 [TRACE]: API:isConfigured()
Mon Nov  4 15:53:46 2024 [TRACE]: API:_createUrl(/diagnostics.xml)
Mon Nov  4 15:53:46 2024 [TRACE]: Http:request(GET, http://[USERNAME]:[PASSWORD]@[IP]/diagnostics.xml, nil, nil, {"return_http_failure":true})
Mon Nov  4 15:53:46 2024 [TRACE]: Http:getDefaultTimeout()
Mon Nov  4 15:53:46 2024 [ERROR]: An error occurred refreshing status; driver.lua:5157: Unbalanced Tag (/BODY) [char=177]
Mon Nov  4 15:53:46 2024 [TRACE]: Http:getDefaultTimeout()
Mon Nov  4 15:53:51 2024 [TRACE]: API:hasAuthenticationFailure()
```

**Comment by black-ops-drivers** [comment]
I have an idea on what the issue is now but will have to get an updated version tomorrow

**Comment by black-ops-drivers** [comment]
Try this version.

[control4-controlbyweb.zip](https://github.com/user-attachments/files/17634628/control4-controlbyweb.zip)

**Comment by joshtbernstein** [comment]
Same result as https://github.com/black-ops-drivers/control4-controlbyweb/issues/4#issuecomment-2455943311
